### ISSUE TITLE
Mentor list abandoned?

### ISSUE THREAD

**Issue by JoeDoyle23** [node-forward/mentors#65]
I noticed that none of the pull requests have been accepted for the last few months. Has this concept been abandoned?

**Comment by hemanth** [comment]
[Fill out this form](https://docs.google.com/forms/d/12OC7RgjoBvypP1HA2yBVgG31OdCSRbW4sXHMaZec0Jo/viewform) to sign up as a mentor or mentee.

**Comment by jasonrhodes** [comment]
This is partly my fault—I'd said I would move over existing mentors into the new Google list and then put out some kind of communication about the new process, but I've been slammed with a new job and a few other things for the last few months and haven't gotten around to it. Still pretty slammed, actually, but I intend to return here at some point, hopefully soon :-/

**Comment by JoeDoyle23** [comment]
@jasonrhodes Ok, no worries. Thanks for the update.

**Comment by hemanth** [comment]
@jasonrhodes I can be of some help, if needed ;)
